// #define MASTER_LEFT
// #define MASTER_RIGHT
#define EE_HANDS

#define SPLIT_OLED_ENABLE

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 2000

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MK_C_OFFSET_UNMOD 16
#define MK_C_INTERVAL_UNMOD 16
#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 32
#define MK_C_OFFSET_1 4
#define MK_C_INTERVAL_1 16
#define MK_C_OFFSET_2 42
#define MK_C_INTERVAL_2 8
